[package]
name = "seye_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
libc = "0.2"
rayon = "1.10.0"
regex = "1.11.1"
chksum-md5 = "0.1.0"
rand = "0.9.1"
